/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*!40000 ALTER TABLE `permissions` DISABLE KEYS */;
INSERT INTO `permissions` (`id`, `name`, `display_name`, `description`, `created_at`, `updated_at`) VALUES
	(1, 'TurmaController@listar', 'turma.index', 'Turma', NULL, NULL),
	(2, 'TurmaController@cadastrar', 'turma.create', 'Turma', NULL, NULL),
	(3, 'TurmaController@editar', 'turma.edit', 'Turma', NULL, NULL),
	(4, 'TurmaController@deletar', 'turma.delete', 'Turma', NULL, NULL),
	(5, 'TurmaController@pesquisar', 'turma.pesquisar', 'Turma', NULL, NULL),
	(12, 'ProfessorController@listar', 'professor.listar', 'Professor', NULL, NULL),
	(13, 'ProfessorController@cadastrar', 'professor.create', 'Professor', NULL, NULL),
	(14, 'ProfessorController@salvar', 'professor.salvar', 'Professor', NULL, NULL),
	(15, 'ProfessorController@editar', 'professor.editar', 'Professor', NULL, NULL),
	(16, 'ProfessorController@pesquisar', 'professor.pesquisar', 'Professor', NULL, NULL),
	(17, 'ProfessorController@deletar', 'professor.deletar', 'Professor', NULL, NULL),
	(18, 'CursoController@listar', 'curso.listar', '', NULL, NULL),
	(19, 'CursoController@cadastrar', 'curso.create', '', NULL, NULL),
	(20, 'CursoController@salvar', 'curso.salvar', '', NULL, NULL),
	(21, 'CursoController@editar', 'curso.editar', '', NULL, NULL),
	(22, 'CursoController@pesquisar', 'curso.pesquisar', '', NULL, NULL),
	(23, 'CursoController@deletar', 'curso.deletar', '', NULL, NULL),
	(24, 'EscolaController@listar', 'escola.listar', '', NULL, NULL),
	(25, 'EscolaController@cadastrar', 'escola.create', '', NULL, NULL),
	(26, 'EscolaController@salvar', 'escola.salvar', '', NULL, NULL),
	(27, 'EscolaController@editar', 'escola.editar', '', NULL, NULL),
	(28, 'EscolaController@pesquisar', 'escola.pesquisar', '', NULL, NULL),
	(29, 'EscolaController@deletar', 'escola.deletar', '', NULL, NULL),
	(30, 'DisciplinaController@listar', 'disciplina.listar', '', NULL, NULL),
	(31, 'DisciplinaController@cadastrar', 'disciplina.create', '', NULL, NULL),
	(32, 'DisciplinaController@salvar', 'disciplina.salvar', '', NULL, NULL),
	(33, 'DisciplinaController@editar', 'disciplina.editar', '', NULL, NULL),
	(34, 'DisciplinaController@pesquisar', 'disciplina.pesquisar', '', NULL, NULL),
	(35, 'DisciplinaController@deletar', 'disciplina.deletar', '', NULL, NULL),
	(36, 'AlunoController@listar', 'aluno.listar', '', NULL, NULL),
	(37, 'AlunoController@cadastrar', 'aluno.create', '', NULL, NULL),
	(38, 'AlunoController@salvar', 'aluno.salvar', '', NULL, NULL),
	(39, 'AlunoController@editar', 'aluno.editar', '', NULL, NULL),
	(40, 'AlunoController@pesquisar', 'aluno.pesquisar', '', NULL, NULL),
	(41, 'AlunoController@deletar', 'aluno.deletar', '', NULL, NULL),
	(42, 'AvaliacaoController@listar', 'avaliacao.listar', '', NULL, NULL),
	(43, 'AvaliacaoController@cadastrar', 'avaliacao.create', '', NULL, NULL),
	(44, 'AvaliacaoController@salvar', 'avaliacao.salvar', '', NULL, NULL),
	(45, 'AvaliacaoController@editar', 'avaliacao.editar', '', NULL, NULL),
	(46, 'AvaliacaoController@pesquisar', 'avaliacao.pesquisar', '', NULL, NULL),
	(47, 'AvaliacaoController@deletar', 'avaliacao.deletar', '', NULL, NULL),
	(48, 'MatriculaController@index', 'matricula.listar', '', NULL, NULL),
	(49, 'MatriculaController@create', 'matricula.create', '', NULL, NULL),
	(50, 'MatriculaController@store', 'matricula.store', '', NULL, NULL),
	(51, 'MatriculaController@update', 'matricula.update', '', NULL, NULL),
	(52, 'MatriculaController@edit', 'matricula.edit', '', NULL, NULL),
	(53, 'MatriculaController@pesquisar', 'matricula.pesquisar', '', NULL, NULL),
	(54, 'MatriculaController@search', 'matricula.search', '', NULL, NULL),
	(55, 'MatriculaController@destroy', 'matricula.deletar', '', NULL, NULL),
	(56, 'DisciplinaTurmaController@index', 'disciplina_turma.listar', '', NULL, NULL),
	(57, 'DisciplinaTurmaController@create', 'disciplina_turma.create', '', NULL, NULL),
	(58, 'DisciplinaTurmaController@store', 'disciplina_turma.store', '', NULL, NULL),
	(59, 'DisciplinaTurmaController@update', 'disciplina_turma.update', '', NULL, NULL),
	(60, 'DisciplinaTurmaController@edit', 'disciplina_turma.edit', '', NULL, NULL),
	(61, 'DisciplinaTurmaController@pesquisar', 'disciplina_turma.pesquisar', '', NULL, NULL),
	(62, 'DisciplinaTurmaController@search', 'disciplina_turma.search', '', NULL, NULL),
	(63, 'DisciplinaTurmaController@destroy', 'disciplina_turma.deletar', '', NULL, NULL),
	(64, 'GeralPDFController@professorDisciplina', 'professorDisciplina.pdf', '', NULL, NULL),
	(65, 'GeralPDFController@curso', 'curso.pdf', '', NULL, NULL),
	(66, 'AvaliacaoController@exibir', 'avaliacao.exibir', NULL, NULL, NULL),
	(68, 'ProfessorDisciplinaController@index', 'ProfessorDisciplina.index', NULL, NULL, NULL),
	(69, 'ProfessorDisciplinaController@store', 'ProfessorDisciplina.store', NULL, NULL, NULL),
	(70, 'ProfessorDisciplinaController@edit', 'ProfessorDisciplina.edit', NULL, NULL, NULL),
	(71, 'ProfessorDisciplinaController@update', 'ProfessorDisciplina.update', NULL, NULL, NULL),
	(72, 'ProfessorDisciplinaController@destroy', 'ProfessorDisciplina.destroy', NULL, NULL, NULL),
	(73, 'AvaliacaoAlunoController@listar', 'AvaliacaoAluno.listar', NULL, NULL, NULL),
	(74, 'AvaliacaoAlunoController@salvar', 'AvaliacaoAluno.salvar', NULL, NULL, NULL),
	(75, 'AvaliacaoAlunoController@exibir', 'AvaliacaoAluno.exibir', NULL, NULL, NULL),
	(77, 'AvaliacaoAlunoController@editar', 'AvaliacaoAluno.editar', NULL, NULL, NULL),
	(78, 'AvaliacaoAlunoController@deletar', 'AvaliacaoAluno.deletar', NULL, NULL, NULL),
	(79, 'ResponsavelAlunoController@listar', 'Responsavel.listar', NULL, NULL, NULL),
	(80, 'ResponsavelAlunoController@cadastrar', 'Reponsavel.cadastrar', NULL, NULL, NULL),
	(81, 'AvaliacaoAlunoController@cadastrar', 'Avaliacao.cadastrar', NULL, NULL, NULL),
	(82, 'TurmaController@salvar', 'turma.salvar', NULL, NULL, NULL),
	(83, 'AvaliacaoAlunoController@graficoIndividual', 'avaliacaoAluno.graficoIndividual', NULL, NULL, NULL),
	(84, 'AvaliacaoController@graficoTurma', 'Avaliacao.graficoTurma', NULL, NULL, NULL),
	(85, 'ResponsavelAlunoController@salvar', 'ResponsavelAluno.salvar', NULL, NULL, NULL),
	(86, 'ResponsavelAlunoController@editar', 'ResponsavelAluno.editar', NULL, NULL, NULL),
	(87, 'ResponsavelAlunoController@deletar', 'ResponsavelAluno.deletar', NULL, NULL, NULL),
	(88, 'ResponsavelAlunoController@pesquisar', 'ResponsavelAluno.pesquisar', NULL, NULL, NULL);
/*!40000 ALTER TABLE `permissions` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
